### ISSUE TITLE
When I use the 3.3.0 version to run Tools/MyProject.Migrator, vs2017 prompt me "Application in break mode"

### ISSUE THREAD

**Issue by tanshanli** [aspnetboilerplate/aspnetboilerplate-templates#77] opened 2018-04-27 11:00 UTC
Operating system：win10 x64
Abp Version：3.3.0 （The latest version of the website download ，2018/4/27）
MyProject EF Model：Code First
My goal：To deploy the project to the server

**Comment by tanshanli** [comment] 2018-04-27 15:17
@ismcagdas 
my console show：
未经处理的异常:  System.IO.FileLoadException: 未能加载文件或程序集“Castle.Core, Version=4.1.1.0, Culture=neutral, PublicKeyToken=407dd0808d44fbdc”或它的某一个依赖项。找到的程序集清单定义与程序集引用不匹配。 (异常来自 HRESULT:0x80131040) ---> System.IO.FileLoadException: 未能加载文件或程序集“Castle.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=407dd0808d44fbdc”或它的某一个依赖项。找到的程序集清单定义与程序集引用不匹配。 (异常来自 HRESULT:0x80131040)
   --- 内部异常堆栈跟踪的结尾 ---
   在 BugManager.Migrator.Program.Main(String[] args)

translate ：
Untreated exception: System. IO. FileLoadException: failed to load file or assembly 'Castle. Core, Version = 4.1.1.0, Culture = neutral, PublicKeyToken = 407 dd0808d44fbdc "or one of its dependencies.
Find the assembly list definition and assembly reference does not match.
(abnormal from HRESULT: 0 x80131040) - > System. IO. FileLoadException: failed to load file or assembly 'Castle. Core, Version = 4.0.0.0, Culture = neutral, PublicKeyToken = 407 dd0808d44fbdc "or one of its dependencies.
Find the assembly list definition and assembly reference does not match.
(abnormal from HRESULT: 0 x80131040) - at the end of the inner exception stack trace - in BugManager. The Migrator. The Program. The Main (String [] args)

**Comment by tanshanli** [comment] 2018-04-27 15:30
@ismcagdas I notice the project packages.config  are 
`<package id="Castle.Core" version="4.2.1" targetFramework="net461" />`
but I can't understand why the error message is  **Castle.Core, Version=4.1.1.0**

**Comment by acjh** [comment] 2018-04-27 15:34
Duplicate of aspnetboilerplate/aspnetboilerplate#2902

**Comment by tanshanli** [comment] 2018-04-27 15:39
@acjh 非常感谢，在app.config中将Castle.Core设置为 newVersion="4.0.0.0"就可以了。
原本是 newVersion="4.1.1.0"

**Closed** 2018-06-09 16:00 UTC
