### ISSUE TITLE
Login action check returnUrl for scripts

### ISSUE THREAD

**Issue by hikalkan** [aspnetboilerplate/aspnetboilerplate-templates#50] opened 2017-03-06 12:01 UTC
see https://github.com/aspnetboilerplate/aspnetboilerplate/issues/1901

**Comment by ismcagdas** [comment] 2018-01-02 06:26
Closing because couldn't get a response from @ron194. We can reopen if we can reproduce it.

**Closed by ismcagdas** 2018-01-02 06:26 UTC
Labels: enhancement
